name: Sigyn Agent

on:
  push:
    branches: [main]

  pull_request:
    paths:
      - "package-lock.json"
      - "src/agent/**"
      - ".github/workflows/agent.yml"
      - "!src/agent/**/*.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Unit tests
        uses: Wandalen/wretry.action@e68c23e6309f2871ca8ae4763e7629b9c258e1ea # v3.8.0
        with:
          command: npm ci && npm run build && npm run test --workspace=src/agent
          attempt_limit: 3
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Run e2e tests
        run: npm run test:e2e --workspace=src/agent
