name: Sigyn Agent

on:
  push:
    branches: [main]
    
  pull_request:
    paths:
      - "package-lock.json"
      - "src/agent/**"
      - ".github/workflows/agent.yml"
      - "!src/agent/**/*.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Unit tests
        uses: Wandalen/wretry.action@6feedb7dedadeb826de0f45ff482b53b379a7844 # v3.5.0
        with:
          command: npm ci && npm run build && npm run test --workspace=src/agent
          attempt_limit: 3
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Run e2e tests
        run: npm run test:e2e --workspace=src/agent
