name: Sigyn Agent

on:
  push:
    branches: [main]
    
  pull_request:
    paths:
      - "package-lock.json"
      - "src/agent/**"
      - ".github/workflows/agent.yml"
      - "!src/agent/**/*.md"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
        with:
          egress-policy: audit
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Unit tests
        uses: Wandalen/wretry.action@6feedb7dedadeb826de0f45ff482b53b379a7844 # v3.5.0
        with:
          command: npm ci && npm run build && npm run test --workspace=src/agent
          attempt_limit: 3
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Run e2e tests
        run: npm run test:e2e --workspace=src/agent
